#!/usr/bin/env node
/**
 * pre-compact.mjs
 * Fires on PreCompact (last chance before Claude auto-compacts context).
 * Writes an emergency handoff so no state is lost on compaction.
 * Install: .claude/hooks/pre-compact.mjs
 */

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import { join } from 'path';

const input = JSON.parse(readFileSync('/dev/stdin', 'utf8'));

const now = new Date();
const timestamp = now.toISOString()
  .replace('T', '-')
  .replace(/:/g, '-')
  .substring(0, 16);

const dir = 'docs/handoffs';
if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

const filename = join(dir, `${timestamp}-auto-compact-handoff.md`);

const content = `---
auto-generated: true
trigger: pre-compact
timestamp: ${now.toISOString()}
---

## Auto-compact handoff

Context was compacted automatically. This file was generated by the
pre-compact hook to preserve session state.

## What to do

1. Start a fresh session
2. Run /fl-session-start
3. Load this handoff when prompted
4. Review what was in progress and continue from last known state

## Last known context summary

${input.summary ?? 'No summary available - check recent commits and docs/plans/ for current state.'}
`;

writeFileSync(filename, content);

console.log(JSON.stringify({
  type: 'notification',
  message: `Auto-compact handoff saved to ${filename}`
}));

process.exit(0);
